version: "3.7"
services:
  server:
    image: kukker/code-server:latest
    command: ["--host", "0.0.0.0", "--cert"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      PASSWORD: 1234
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/workspace:/home/coder/project
    networks:
      - outside

networks:
  outside:
    external: true
    name: "host"
