name: Docker Image CI

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag code-server:latest
    - name: Login to GitHub Package Repository
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
      run: |
        docker login docker.pkg.github.com -u publisher -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
    - name: Tag Docker image
      run: |
        docker tag code-server:latest docker.pkg.github.com/kukkerem/code-server/code-server:$(date +%s)
        docker tag code-server:latest docker.pkg.github.com/kukkerem/code-server/code-server:${GITHUB_SHA:0:39}
    - name: Push Docker image
      run: |
        docker push docker.pkg.github.com/Kukkerem/code-server/code-server
    - name: Tag latest if develop
      if: github.ref == 'refs/heads/develop'
      run: |
        # we push latest separate so it shows up as latest in the UI
        docker tag code-server:latest docker.pkg.github.com/kukkerem/code-server/code-server:latest
        docker push docker.pkg.github.com/kukkerem/code-server/code-server:latest
